name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run:
    name: On ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
      actions: write
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: eifinger/setup-rye@v2
        with:
          enable-cache: true

      - name: Sync dependencies
        run: rye sync --no-lock

      - name: Check code
        run: |
          rye lint
          rye run check-types
          
      - name: Run no benchmarked tests
        run: rye test -- --benchmark-skip
      
      - name: Run benchmarks
        run: rye test --  --benchmark-only --benchmark-json output.json
      
      - name: Upload results
        if: github.ref_name == 'main'
        uses: actions/upload-artifact@v4
        with:
          name: benchmark_results
          path: output.json
          retention-days: 90
          overwrite: true

      - name: Download previous result
        if: github.event_name == 'pull_request'
        uses: actions/download-artifact@v4
        with:
          name: benchmark_results
          path: output.json
        continue-on-error: true

      - name: Publish results
        if: github.event_name == 'pull_request'
        uses: nils-braun/pytest-benchmark-commenter@v2
        with:
          benchmark-file: output.json
          comparison-benchmark-file: "old_benchmark/output.json"